/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    war
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.jakarta.servlet.jsp.jstl.jakarta.servlet.jsp.jstl.api)
    api(libs.org.glassfish.web.jakarta.servlet.jsp.jstl)
    api(libs.com.mysql.mysql.connector.j)
    api(libs.com.sun.mail.javax.mail)
    api(libs.com.google.guava.guava)
    api(libs.com.google.code.gson.gson)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
    compileOnly(libs.jakarta.servlet.jakarta.servlet.api)
    compileOnly(libs.jakarta.servlet.jsp.jakarta.servlet.jsp.api)
}

group = "com.example"
version = "1.0-SNAPSHOT"
description = "TTW_BanMayInVaVatTuVanPhong"
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
